### PR TITLE
Add sendBinaryFrame method accepting payload with provided offset

### PR DESCRIPTION
**Pull request by SviatlanaMatsiuk**

### CODE REVIEW

**Comment by magnus-gustafsson** [comment]
Thanks for creating the pull request.
I think that the signature on `WebSocketConnection.sendBinaryFrame is incorrect`. There is no way to indicate if the frame is a final frame or not in the new method.
An better design would be `CompletableFuture<Void> sendBinaryFrame(byte[] payload, int offset, int length, boolean finalFragment, int rsv)`

`WebSocketSender` can also then be simplified, it only needs to have one method with the same signature.

The new method you added in `WebSocketSender` seems to contain multiple bugs as well, it uses `payload.length` in multiple places instead of the supplied `length` parameter.

**Comment by SviatlanaMatsiuk** [comment]
> Thanks for creating the pull request. I think that the signature on `WebSocketConnection.sendBinaryFrame is incorrect`. There is no way to indicate if the frame is a final frame or not in the new method. An better design would be `CompletableFuture<Void> sendBinaryFrame(byte[] payload, int offset, int length, boolean finalFragment, int rsv)`
> 
> `WebSocketSender` can also then be simplified, it only needs to have one method with the same signature.
> 
> The new method you added in `WebSocketSender` seems to contain multiple bugs as well, it uses `payload.length` in multiple places instead of the supplied `length` parameter.

Thank you for your feedback.
I added parameter `boolean finalFragment` to the signature. Also I replaced `WebSocketSender` method to have 2 optional parameters: offset and length, to avoid code duplication. So that the new method is only different from the previous one by following lines:

```
WebSocketFrame webSocketFrame = Stream.of(offset, length).allMatch(Optional::isPresent) 
				? nextContiuationFrame.create(finalFragment, rsv, Unpooled.copiedBuffer(payload, offset.get(), length.get()))
				: nextContiuationFrame.create(finalFragment, rsv, Unpooled.copiedBuffer(payload));

```

**Comment by magnus-gustafsson** [comment]
Hi,
Please don't use `Optional` for wrapping primitive value types in parameters. They don't fulfill any need and causes more object allocation. The `Optional` wrapping the `Integer` which wraps the primitive `int`.
Instead of `Optional` you can just call the method with the payload full length and 0 offset, like:
`webSocketSender.sendBinaryFrame(channel, payload, true, 0, payload.length, 0)`
The `finalFragment` parameter should really be placed after `length`, but before `rsv`. The method signature will then be more in line with the rest of the method signatures.

**Comment by SviatlanaMatsiuk** [comment]
I fixed the length stuff. If there is anything else - let me know :)

**Comment by magnus-gustafsson** [comment]
Looks good, I'll merge.

**Pull request merged**
